steps:
  - name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: 'mvn'
    args: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_URI}:latest', '-t', '${_IMAGE_URI}:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URI}']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment/${_DEPLOYMENT_FILE}.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=javajive'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/${_DEPLOYMENT}'
      - '${_CONTAINER_NAME}=${_IMAGE_URI}:$SHORT_SHA'
      - '-n'
      - '${_NAMESPACE}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=phoenix-staging'


substitutions:
  _CONTAINER_NAME: hacksummit22
  _NAMESPACE: hacksummit
  _DEPLOYMENT: hacksummit-deployment
  _DEPLOYMENT_FILE: hacksummit22
  _IMAGE_URI: eu.gcr.io/javajive-001/hacksummit22
